// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultAssetsPath() {
  return window['go']['main']['App']['GetDefaultAssetsPath']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PickAudioFile() {
  return window['go']['main']['App']['PickAudioFile']();
}

export function RenderPreview(arg1) {
  return window['go']['main']['App']['RenderPreview'](arg1);
}

export function Run(arg1) {
  return window['go']['main']['App']['Run'](arg1);
}

export function ShowFileOnExplorer(arg1) {
  return window['go']['main']['App']['ShowFileOnExplorer'](arg1);
}

export function Toast(arg1) {
  return window['go']['main']['App']['Toast'](arg1);
}
