// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetDefaultAssetsPath():Promise<types.GetDefaultAssetsPathResponse>;

export function OpenURL(arg1:string):Promise<void>;

export function PickAudioFile():Promise<types.PickAudioFileResponse>;

export function RenderPreview(arg1:types.Config):Promise<types.RenderPreviewResponse>;

export function Run(arg1:types.Config):Promise<types.RunResponse>;

export function Toast(arg1:types.ToastConfig):Promise<void>;
